# Generated by Django 5.2.6 on 2025-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(default='images/default.jpg', upload_to='images/')),
                ('brand', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids')], default='', max_length=10)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
