# Generated by Django 5.2.6 on 2025-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
