# Generated by Django 5.2.6 on 2025-12-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_id',
        ),
    ]
